apiVersion: v1
kind: Pod
metadata:
  name: imagepuller
spec:
  containers:
    - name: puller
      image: registry.cn-shanghai.aliyuncs.com/jibutech/imagepuller:latest
      args:
        - -runtime=/hostvarrun
        - -images=redis:latest,redis:alpine
        - --logtostderr=true
        - -v=0
      imagePullPolicy: Always
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: "0"
          memory: "0"
      volumeMounts:
        - mountPath: /hostvarrun
          name: runtime-socket
          readOnly: true
  tolerations:
    - operator: Exists
  hostNetwork: true
  restartPolicy: Never
  terminationGracePeriodSeconds: 10
  volumes:
    - hostPath:
        path: /var/run
        type: ""
      name: runtime-socket
